version: '3'
services:
  dbAFCV1:
    image: postgres
    container_name: postgres_container_AFCV1
    restart: always
    ports:
      - "5433:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres111afcorp
      - POSTGRES_PASSWORD=postgres111AFcorp2023*
      #- DATABASE_HOST=127.0.0.1
    volumes:   # primero se debe crear un volumen respaldo_bd_afcorp
    - /Users/homesis/Documents/Desarrollo/SistemaAFCorp/BasesDatos/BD_AFCV1/DatosAFC1:/var/lib/postgresql/data
  


  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    container_name: web_AFCV1
    volumes: 
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      - dbAFCV1


  