# Generated by Django 3.2.16 on 2023-11-29 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos_red',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_instalacion', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('nodo_actual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodo_actual', to='incidentes.nodo')),
                ('nodo_inicial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodo_inicial', to='incidentes.nodo')),
            ],
        ),
        migrations.CreateModel(
            name='Movimientos_equipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidentes.equipos_red')),
                ('nodo_llegada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodo_llegada', to='incidentes.nodo')),
                ('nodo_salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodo_salida', to='incidentes.nodo')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimientos_equipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('problema', models.TextField()),
                ('solucion', models.TextField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidentes.equipos_red')),
            ],
        ),
    ]
