# Generated by Django 3.2.16 on 2023-11-30 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0003_auto_20231129_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos_red',
            name='alias',
            field=models.TextField(blank=True, null=True),
        ),
    ]
