# Generated by Django 3.2.16 on 2023-12-02 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidentes', '0004_equipos_red_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_fibra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=60)),
                ('numero_hilos', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('marca', models.CharField(max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_trabajo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trazado_FO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.TextField()),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('tipo_fibra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidentes.tipo_fibra')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajos_FO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('tipo_fibra_cambio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidentes.tipo_fibra')),
                ('tipo_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidentes.tipo_trabajo')),
                ('trazado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidentes.trazado_fo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
