# Generated by Django 3.2.16 on 2023-11-17 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subtipo_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtipo', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.TextField()),
                ('descripcion', models.TextField()),
                ('codigo', models.CharField(max_length=30)),
                ('precio_entrada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_salida', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_promo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('seguimiento', models.BooleanField(default=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_modificacion', models.DateField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.estado_producto')),
                ('subtipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.subtipo_producto')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.tipo_producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrecioProductosOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_entrada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_modificacion', models.DateField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.tipo_producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrecioProductosIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_entrada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_modificacion', models.DateField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.tipo_producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
