# Generated by Django 3.2.16 on 2023-11-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturasVentas', '0002_alter_facturasv_plazo_meses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturasv',
            name='observacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
