# Generated by Django 3.2.16 on 2023-11-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturasVentas', '0003_alter_facturasv_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturasv',
            name='fecha',
            field=models.DateField(),
        ),
    ]
