# Generated by Django 3.2.16 on 2023-11-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturasVentas', '0004_alter_facturasv_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturasv',
            name='factura_cerrada',
            field=models.BooleanField(default=False),
        ),
    ]
