# Generated by Django 3.2.16 on 2023-11-29 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generalAFC', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facturasVentas', '0005_facturasv_factura_cerrada'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleFacturaV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generalAFC.bodega')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generalAFC.empresa_corp')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturasVentas.facturasv')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
