# Generated by Django 3.2.16 on 2023-12-07 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generalAFC', '0001_initial'),
        ('facturasVentas', '0006_detallefacturav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallefacturav',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generalAFC.empresa_corp'),
        ),
    ]
